#!/usr/bin/env bash

main() {
  start
  copy_library
  copy_nukshuk
  copy_studio
  copy_ssh
  copy_bash
  copy_aws_global
  copy_other
  end
}

start() {
  echo '---PUSHING UNITY---'
  rm *.zip -rf
}

copy_nukshuk() {
  mkdir -p ./nukshuk

  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql','Pods'} ~/nukshuk/ios ./nukshuk/ios -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/nukshuk/api ./nukshuk/api -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/nukshuk/coach ./nukshuk/coach -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/nukshuk/android ./nukshuk/android -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/nukshuk/nuknetwork ./nukshuk/nuknetwork -r
}

copy_studio() {
  mkdir -p ./studio

  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/studio/laravel-docker ./studio/laravel-docker -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/studio/mastery ./studio/mastery -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/studio/rxtest ./studio/rxtest -r
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/studio/yieldable ./studio/yieldable -r
}

copy_library() {
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/library . -r
}

copy_ssh() {
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.ssh . -r
}

copy_bash() {
  mkdir -p bash
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.bashrc bash
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.bash_aliases bash
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.bash_env bash
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.profile bash
}

copy_aws_global() {
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.aws . -r
}

copy_other() {
  mkdir -p other
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.config/user-dirs.dirs other
  rsync -rv --exclude={'node_modules','vendor','gradle','dist','.git','*.sql'} ~/.pgpass other
}

end() {
  now=$(date +'%Y-%m-%d')
  archivefile="archive_${now}.zip"
  echo "Creating ${archivefile}..."
  read -s -p "Enter Password: " password
  # zipping
  zip -r -q -5 $archivefile .aws .ssh bash library nukshuk other studio -P $password 2> /dev/null 
  # cleanup
  rm .aws .ssh api bash library nukshuk other studio -rf
  # push
  git add .
  git commit -m $archivefile
  git push
}

main